/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 805398
 */
public class DoubleJeopardy extends javax.swing.JFrame {
     int CurrentQuestion ;
     int Score;
     
    /**
     * Creates new form Scene1
     */
    public DoubleJeopardy(int Score) {
        this.Score = Score;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Box2001 = new javax.swing.JButton();
        Box6001 = new javax.swing.JButton();
        Box8001 = new javax.swing.JButton();
        Box4001 = new javax.swing.JButton();
        Box10001 = new javax.swing.JButton();
        Box10002 = new javax.swing.JButton();
        Box2002 = new javax.swing.JButton();
        Box6002 = new javax.swing.JButton();
        Box8002 = new javax.swing.JButton();
        Box4002 = new javax.swing.JButton();
        Box4003 = new javax.swing.JButton();
        Box6003 = new javax.swing.JButton();
        Box8003 = new javax.swing.JButton();
        Box10003 = new javax.swing.JButton();
        Box2003 = new javax.swing.JButton();
        Box10004 = new javax.swing.JButton();
        Box6004 = new javax.swing.JButton();
        Box2004 = new javax.swing.JButton();
        Box4004 = new javax.swing.JButton();
        Box8004 = new javax.swing.JButton();
        Box2005 = new javax.swing.JButton();
        Box6005 = new javax.swing.JButton();
        Box8005 = new javax.swing.JButton();
        Box4005 = new javax.swing.JButton();
        Box10005 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScoreBox = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AnswerBox = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        QuestionBox = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        scoremagic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("                         Jeopardy");
        jLabel1.setOpaque(true);

        Box2001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2001.setForeground(new java.awt.Color(0, 255, 0));
        Box2001.setText("400");
        Box2001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2001ActionPerformed(evt);
            }
        });

        Box6001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6001.setForeground(new java.awt.Color(0, 255, 0));
        Box6001.setText("1200");
        Box6001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6001ActionPerformed(evt);
            }
        });

        Box8001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8001.setForeground(new java.awt.Color(0, 255, 0));
        Box8001.setText("1600");
        Box8001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8001ActionPerformed(evt);
            }
        });

        Box4001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4001.setForeground(new java.awt.Color(0, 255, 0));
        Box4001.setText("800");
        Box4001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4001ActionPerformed(evt);
            }
        });

        Box10001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10001.setForeground(new java.awt.Color(0, 255, 0));
        Box10001.setText("2000");
        Box10001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10001ActionPerformed(evt);
            }
        });

        Box10002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10002.setForeground(new java.awt.Color(0, 255, 0));
        Box10002.setText("2000");
        Box10002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10002ActionPerformed(evt);
            }
        });

        Box2002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2002.setForeground(new java.awt.Color(0, 255, 0));
        Box2002.setText("400");
        Box2002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2002ActionPerformed(evt);
            }
        });

        Box6002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6002.setForeground(new java.awt.Color(0, 255, 0));
        Box6002.setText("1200");
        Box6002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6002ActionPerformed(evt);
            }
        });

        Box8002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8002.setForeground(new java.awt.Color(0, 255, 0));
        Box8002.setText("1600");
        Box8002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8002ActionPerformed(evt);
            }
        });

        Box4002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4002.setForeground(new java.awt.Color(0, 255, 0));
        Box4002.setText("800");
        Box4002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4002ActionPerformed(evt);
            }
        });

        Box4003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4003.setForeground(new java.awt.Color(0, 255, 0));
        Box4003.setText("800");
        Box4003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4003ActionPerformed(evt);
            }
        });

        Box6003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6003.setForeground(new java.awt.Color(0, 255, 0));
        Box6003.setText("1200");
        Box6003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6003ActionPerformed(evt);
            }
        });

        Box8003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8003.setForeground(new java.awt.Color(0, 255, 0));
        Box8003.setText("1600");
        Box8003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8003ActionPerformed(evt);
            }
        });

        Box10003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10003.setForeground(new java.awt.Color(0, 255, 0));
        Box10003.setText("2000");
        Box10003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10003ActionPerformed(evt);
            }
        });

        Box2003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2003.setForeground(new java.awt.Color(0, 255, 0));
        Box2003.setText("400");
        Box2003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2003ActionPerformed(evt);
            }
        });

        Box10004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10004.setForeground(new java.awt.Color(0, 255, 0));
        Box10004.setText("2000");
        Box10004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10004ActionPerformed(evt);
            }
        });

        Box6004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6004.setForeground(new java.awt.Color(0, 255, 0));
        Box6004.setText("1200");
        Box6004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6004ActionPerformed(evt);
            }
        });

        Box2004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2004.setForeground(new java.awt.Color(0, 255, 0));
        Box2004.setText("400");
        Box2004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2004ActionPerformed(evt);
            }
        });

        Box4004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4004.setForeground(new java.awt.Color(0, 255, 0));
        Box4004.setText("800");
        Box4004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4004ActionPerformed(evt);
            }
        });

        Box8004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8004.setForeground(new java.awt.Color(0, 255, 0));
        Box8004.setText("1600");
        Box8004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8004ActionPerformed(evt);
            }
        });

        Box2005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2005.setForeground(new java.awt.Color(0, 255, 0));
        Box2005.setText("400");
        Box2005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2005ActionPerformed(evt);
            }
        });

        Box6005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6005.setForeground(new java.awt.Color(0, 255, 0));
        Box6005.setText("1200");
        Box6005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6005ActionPerformed(evt);
            }
        });

        Box8005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8005.setForeground(new java.awt.Color(0, 255, 0));
        Box8005.setText("1600");
        Box8005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8005ActionPerformed(evt);
            }
        });

        Box4005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4005.setForeground(new java.awt.Color(0, 255, 0));
        Box4005.setText("800");
        Box4005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4005ActionPerformed(evt);
            }
        });

        Box10005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10005.setForeground(new java.awt.Color(0, 255, 0));
        Box10005.setText("2000");
        Box10005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10005ActionPerformed(evt);
            }
        });

        C1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        C1.setText("Kardashians");
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });

        C2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        C2.setText("Asia");
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });

        C3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        C3.setText("Actors");
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });

        C4.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        C4.setText("Double EE's");
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });

        C5.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        C5.setText("Ohio");
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Your Score");

        ScoreBox.setColumns(20);
        ScoreBox.setRows(5);
        jScrollPane1.setViewportView(ScoreBox);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("The Question");

        jButton1.setText("Click Here!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(153, 255, 102));
        jLabel4.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel4.setText("Your Answer");

        AnswerBox.setColumns(20);
        AnswerBox.setRows(5);
        jScrollPane3.setViewportView(AnswerBox);

        QuestionBox.setBackground(new java.awt.Color(0, 255, 255));
        QuestionBox.setOpaque(true);

        jButton2.setText("Pass");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Daily double = your * 2");

        jLabel7.setText("Daily Triple = your * 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box4001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Box4002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box2001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Box2002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box8001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Box8002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box6001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Box6002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box10001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Box10002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(513, 513, 513))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scoremagic, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box2003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box4003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box6003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box8003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box10003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box2004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box4004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box6004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box8004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box10004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Box10005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box8005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box6005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box4005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box2005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 250, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(568, 568, 568)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuestionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(551, 551, 551))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scoremagic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(QuestionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box2004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box2005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box2003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box2002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box2001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box4004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box4005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box4003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box4002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box4001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box6004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box6005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box6003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box6002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box6001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box8004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box8005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box8003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box8002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box8001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Box10004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box10005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box10003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box10002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box10001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Box2001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2001ActionPerformed
    QuestionBox.setText("The Oldest Kardashian Sister");
    AnswerBox.getText();
        CurrentQuestion = 2001;
        Box2001.setText("");
        this.remove(Box2001) ;
        repaint();
    }//GEN-LAST:event_Box2001ActionPerformed

    private void Box8001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8001ActionPerformed
    QuestionBox.setText("Kendall Jenner's father"); 
    AnswerBox.getText();
        CurrentQuestion = 8001;
        Box8001.setText("");
        this.remove(Box8001) ;
        repaint();
    }//GEN-LAST:event_Box8001ActionPerformed

    private void Box2002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2002ActionPerformed
    QuestionBox.setText("Biggest Country in Aisa");
    AnswerBox.getText();
        CurrentQuestion = 2002;
        Box2002.setText("");
        this.remove(Box2002) ;
        repaint();
    }//GEN-LAST:event_Box2002ActionPerformed

    private void Box8002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8002ActionPerformed
    QuestionBox.setText("North and South K ");
    AnswerBox.getText();
        CurrentQuestion = 8002;
        Box8002.setText("");
        this.remove(Box8002) ;
        repaint();
    }//GEN-LAST:event_Box8002ActionPerformed

    private void Box8003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8003ActionPerformed
    QuestionBox.setText("He Played Hulk in Avengers: EndGame");
    AnswerBox.getText();
        CurrentQuestion = 8003;
        Box8003.setText("");
        this.remove(Box8003) ;
        repaint();
    }//GEN-LAST:event_Box8003ActionPerformed

    private void Box2003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2003ActionPerformed
    QuestionBox.setText("He plays Ironman in Marvel Movies");
    AnswerBox.getText();
        CurrentQuestion = 2003;
        Box2003.setText("");
        this.remove(Box2003) ;
        repaint();
    }//GEN-LAST:event_Box2003ActionPerformed

    private void Box2004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2004ActionPerformed
    QuestionBox.setText("It Produces Wool");
    AnswerBox.getText();
        CurrentQuestion = 2004;
        Box2004.setText("");
        this.remove(Box2004) ;
        repaint();
    }//GEN-LAST:event_Box2004ActionPerformed

    private void Box8004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8004ActionPerformed
    QuestionBox.setText("You Dive ......");
    scoremagic.setText(" Daily Double ");
    AnswerBox.getText();
        CurrentQuestion = 8004;
        Box8004.setText("");
        this.remove(Box8004) ;
        repaint();
    }//GEN-LAST:event_Box8004ActionPerformed

    private void Box2005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2005ActionPerformed
    QuestionBox.setText("The first ambulance service was established in Cincinnati in");
    AnswerBox.getText();
        CurrentQuestion = 2005;
        Box2005.setText("");
        this.remove(Box2005) ;
        repaint();
    }//GEN-LAST:event_Box2005ActionPerformed

    private void Box8005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8005ActionPerformed
     QuestionBox.setText("Ohio's Largest City by Size");
     scoremagic.setText(" Daily Triple ");
     AnswerBox.getText();
        CurrentQuestion = 8005;
        Box8005.setText("");
        this.remove(Box8005) ;
        repaint();
    }//GEN-LAST:event_Box8005ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
       
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
      
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
         
    }//GEN-LAST:event_C4ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
       
    }//GEN-LAST:event_C5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    if (CurrentQuestion  == 2001 ){
        if ("Kourtney Kardashian".equalsIgnoreCase(AnswerBox.getText())){
            Score += 400;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 2001){
            Score -= 400;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 2002 ){
        if ("Russia".equalsIgnoreCase(AnswerBox.getText())){
            Score += 400;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 2002 ){
            Score -= 400;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 2003 ){
        if ("Robert Downey Jr".equalsIgnoreCase(AnswerBox.getText())){
            Score += 400;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 2003 ){
            Score -= 400;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 2004 ){
        if ("Sheep".equalsIgnoreCase(AnswerBox.getText())){
            Score += 400;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 2004 ){
            Score -= 400;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 2005 ){
        if ("1865".equalsIgnoreCase(AnswerBox.getText())){
            Score += 400;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 2005 ){
            Score -= 400;
            ScoreBox.setText(" " + Score);
        } 
        }
    
    if (CurrentQuestion  == 4001 ){
        if ("Kanye West".equalsIgnoreCase(AnswerBox.getText())){
            Score += 800;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 4001 ){
            Score -= 800;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 4002 ){
        if ("Iran".equalsIgnoreCase(AnswerBox.getText())){
            Score += 800;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 4002 ){
            Score -= 800;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 4003 ){
        if ("Dwayne Johnson".equalsIgnoreCase(AnswerBox.getText())){
            Score += 800;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 4003 ){
            Score -= 800;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 4004 ){
        if ("Freezes".equalsIgnoreCase(AnswerBox.getText())){
            Score += 800;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 4004 ){
            Score -= 800;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 4005 ){
        if ("Baseball".equalsIgnoreCase(AnswerBox.getText())){
            Score += 800;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 4005 ){
            Score -= 800;
            ScoreBox.setText(" " + Score);
        } 
        }
    
    if (CurrentQuestion  == 6001 ){
        if ("Kylie Cosmetics".equalsIgnoreCase(AnswerBox.getText())){
            Score += 1200;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 6001 ){
            Score -= 1200;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 6002 ){
        if ("Lebanon".equalsIgnoreCase(AnswerBox.getText())){
            Score += 1200;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 6002 ){
            Score -= 1200;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 6003 ){
        if ("John Cena".equalsIgnoreCase(AnswerBox.getText())){
            Score += 1200;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 6003 ){
            Score -= 1200;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 6004 ){
        if ("sweet".equalsIgnoreCase(AnswerBox.getText())){
            Score += 1200;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 6004 ){
            Score -= 1200;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 6005 ){
        if ("Cleveland".equalsIgnoreCase(AnswerBox.getText())){
            Score += 1200;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 6005 ){
            Score -= 1200;
            ScoreBox.setText(" " + Score);
        } 
        }
    
    if (CurrentQuestion  == 8001 ){
        if ("Bruce Jenner".equalsIgnoreCase(AnswerBox.getText())){
            Score += 1600;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 8001 ){
            Score -= 1600;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 8002 ){
        if ("Korea".equalsIgnoreCase(AnswerBox.getText())){
            Score += 1600;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 8002 ){
            Score -= 1600;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 8003 ){
        if ("Mark Ruffalo".equalsIgnoreCase(AnswerBox.getText())){
            Score += 1600;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 8003 ){
            Score -= 1600;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 8004 ){
        if ("deep".equalsIgnoreCase(AnswerBox.getText())){
            Score *= 2;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 8004 ){
            Score -= Score;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 8005 ){
        if ("Zanesville".equalsIgnoreCase(AnswerBox.getText())){
            Score *= 3;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 8005 ){
            Score -= Score;
            ScoreBox.setText(" " + Score);
        } 
        }
    
    if (CurrentQuestion  == 10001 ){
        if ("Kris Jenner".equalsIgnoreCase(AnswerBox.getText())){
            Score += 2000;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 10001 ){
            Score -= 2000;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 10002 ){
        if ("India".equalsIgnoreCase(AnswerBox.getText())){
            Score += 2000;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 10002 ){
            Score -= 2000;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 10003 ){
        if ("Leonardo Dicaprio".equalsIgnoreCase(AnswerBox.getText())){
            Score += 2000;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 10003 ){
            Score -= 2000;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 10004 ){
        if ("speech".equalsIgnoreCase(AnswerBox.getText())){
            Score += 2000;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 10004 ){
            Score -= 2000;
            ScoreBox.setText(" " + Score);
        } 
        }
    if (CurrentQuestion  == 10005 ){
        if ("Jesse Owens".equalsIgnoreCase(AnswerBox.getText())){
            Score += 2000;
            ScoreBox.setText(" " + Score); 
         }
        else if(CurrentQuestion  == 10005 ){
            Score -= 2000;
            ScoreBox.setText(" " + Score);
        } 
        }
    
    AnswerBox.setText("");
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Box4001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4001ActionPerformed
    QuestionBox.setText("The Third husband of Kim Kardashian ");
    AnswerBox.getText();
        CurrentQuestion = 4001;
        Box4001.setText("");
        this.remove(Box4001) ;
        repaint();
    }//GEN-LAST:event_Box4001ActionPerformed

    private void Box6001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6001ActionPerformed
    QuestionBox.setText("The name of Kylie Jenner's Make-up Company");
    AnswerBox.getText();
        CurrentQuestion = 6001;
        Box6001.setText("");
        this.remove(Box6001) ;
        repaint();    
    }//GEN-LAST:event_Box6001ActionPerformed

    private void Box10001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10001ActionPerformed
    QuestionBox.setText("Kim Kardashian's Mother");
    AnswerBox.getText();
        CurrentQuestion = 10001;
        Box10001.setText("");
        this.remove(Box10001) ;
        repaint();
    }//GEN-LAST:event_Box10001ActionPerformed

    private void Box4002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4002ActionPerformed
    QuestionBox.setText("Two Countries with similar names :Iraq and");
    AnswerBox.getText();
        CurrentQuestion = 4002;
        Box4002.setText("");
        this.remove(Box4002) ;
        repaint();    
    }//GEN-LAST:event_Box4002ActionPerformed

    private void Box6002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6002ActionPerformed
    QuestionBox.setText("The Countries Capital is Beirut");
    AnswerBox.getText();
        CurrentQuestion = 6002;
        Box6002.setText("");
        this.remove(Box6002) ;
        repaint();
    }//GEN-LAST:event_Box6002ActionPerformed

    private void Box10002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10002ActionPerformed
    QuestionBox.setText("2nd biggest population in the World and in Asia");
    AnswerBox.getText();
        CurrentQuestion = 10002;
        Box10002.setText("");
        this.remove(Box10002) ;
        repaint();
    }//GEN-LAST:event_Box10002ActionPerformed

    private void Box4003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4003ActionPerformed
    QuestionBox.setText("this Actor is the highest paid in the world");
    AnswerBox.getText();
        CurrentQuestion = 4003;
        Box4003.setText("");
        this.remove(Box4003) ;
        repaint();    
    }//GEN-LAST:event_Box4003ActionPerformed

    private void Box6003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6003ActionPerformed
    QuestionBox.setText("Former Wrestler turned Actor and he starred in the 2018 movie Blockers");
    AnswerBox.getText();
        CurrentQuestion = 6003;
        Box6003.setText("");
        this.remove(Box6003) ;
        repaint();    
    }//GEN-LAST:event_Box6003ActionPerformed

    private void Box10003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10003ActionPerformed
    QuestionBox.setText("He Starred as Jay Gatsby in thr 2013 version of the Movie The Great Gatsby");
    AnswerBox.getText();
        CurrentQuestion = 10003;
        Box10003.setText("");
        this.remove(Box10003) ;
        repaint();
    }//GEN-LAST:event_Box10003ActionPerformed

    private void Box4004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4004ActionPerformed
    QuestionBox.setText("You Put it in the Fridge and it ");
    AnswerBox.getText();
        CurrentQuestion = 4004;
        Box4004.setText("");
        this.remove(Box4004) ;
        repaint();
    }//GEN-LAST:event_Box4004ActionPerformed

    private void Box6004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6004ActionPerformed
    QuestionBox.setText("to many of it is bad for your teeth");
    AnswerBox.getText();
        CurrentQuestion = 6004;
        Box6004.setText("");
        this.remove(Box6004) ;
        repaint();    
    }//GEN-LAST:event_Box6004ActionPerformed

    private void Box10004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10004ActionPerformed
    QuestionBox.setText("MLK Jr.'s Famous I Have a Dream");
    AnswerBox.getText();
        CurrentQuestion = 10004;
        Box10004.setText("");
        this.remove(Box10004) ;
        repaint();
    }//GEN-LAST:event_Box10004ActionPerformed

    private void Box4005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4005ActionPerformed
    QuestionBox.setText("Cincinnati Reds were the first professiona .... Team");
    AnswerBox.getText();
        CurrentQuestion = 4005;
        Box4005.setText("");
        this.remove(Box4005) ;
        repaint();    
    }//GEN-LAST:event_Box4005ActionPerformed

    private void Box6005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6005ActionPerformed
    QuestionBox.setText("This City is Home to the Rock and Roll Hall of Fame");
    AnswerBox.getText();
        CurrentQuestion = 6005;
        Box6005.setText("");
        this.remove(Box6005) ;
        repaint();
    }//GEN-LAST:event_Box6005ActionPerformed

    private void Box10005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10005ActionPerformed
    QuestionBox.setText("He Grew up in Cleveland,Ohio and He won four gold medals in the 1936 Olympics in Berlin");
    AnswerBox.getText();
        CurrentQuestion = 10005;
        Box10005.setText("");
        this.remove(Box10005) ;
        repaint();
    }//GEN-LAST:event_Box10005ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    QuestionBox.setText("");
    AnswerBox.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scene1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scene1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scene1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scene1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scene1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AnswerBox;
    private javax.swing.JButton Box10001;
    private javax.swing.JButton Box10002;
    private javax.swing.JButton Box10003;
    private javax.swing.JButton Box10004;
    private javax.swing.JButton Box10005;
    private javax.swing.JButton Box2001;
    private javax.swing.JButton Box2002;
    private javax.swing.JButton Box2003;
    private javax.swing.JButton Box2004;
    private javax.swing.JButton Box2005;
    private javax.swing.JButton Box4001;
    private javax.swing.JButton Box4002;
    private javax.swing.JButton Box4003;
    private javax.swing.JButton Box4004;
    private javax.swing.JButton Box4005;
    private javax.swing.JButton Box6001;
    private javax.swing.JButton Box6002;
    private javax.swing.JButton Box6003;
    private javax.swing.JButton Box6004;
    private javax.swing.JButton Box6005;
    private javax.swing.JButton Box8001;
    private javax.swing.JButton Box8002;
    private javax.swing.JButton Box8003;
    private javax.swing.JButton Box8004;
    private javax.swing.JButton Box8005;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JLabel QuestionBox;
    private javax.swing.JTextArea ScoreBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField scoremagic;
    // End of variables declaration//GEN-END:variables
}
