/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 805398
 */
public class Scene1 extends javax.swing.JFrame {

    /**
     * Creates new form Scene1
     */
    public Scene1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Box2001 = new javax.swing.JButton();
        Box6001 = new javax.swing.JButton();
        Box8001 = new javax.swing.JButton();
        Box4001 = new javax.swing.JButton();
        Box10001 = new javax.swing.JButton();
        Box10002 = new javax.swing.JButton();
        Box2002 = new javax.swing.JButton();
        Box6002 = new javax.swing.JButton();
        Box8002 = new javax.swing.JButton();
        Box4002 = new javax.swing.JButton();
        Box4003 = new javax.swing.JButton();
        Box6003 = new javax.swing.JButton();
        Box8003 = new javax.swing.JButton();
        Box10003 = new javax.swing.JButton();
        Box2003 = new javax.swing.JButton();
        Box10004 = new javax.swing.JButton();
        Box6004 = new javax.swing.JButton();
        Box2004 = new javax.swing.JButton();
        Box4004 = new javax.swing.JButton();
        Box8004 = new javax.swing.JButton();
        Box2005 = new javax.swing.JButton();
        Box6005 = new javax.swing.JButton();
        Box8005 = new javax.swing.JButton();
        Box4005 = new javax.swing.JButton();
        Box1000 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScoreBox = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        QuestionBox = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AnswerBox = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("                         Jeopardy");
        jLabel1.setOpaque(true);

        Box2001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2001.setForeground(new java.awt.Color(0, 255, 0));
        Box2001.setText("200");
        Box2001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2001ActionPerformed(evt);
            }
        });

        Box6001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6001.setForeground(new java.awt.Color(0, 255, 0));
        Box6001.setText("600");
        Box6001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6001ActionPerformed(evt);
            }
        });

        Box8001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8001.setForeground(new java.awt.Color(0, 255, 0));
        Box8001.setText("800");
        Box8001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8001ActionPerformed(evt);
            }
        });

        Box4001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4001.setForeground(new java.awt.Color(0, 255, 0));
        Box4001.setText("400");
        Box4001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4001ActionPerformed(evt);
            }
        });

        Box10001.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10001.setForeground(new java.awt.Color(0, 255, 0));
        Box10001.setText("1000");
        Box10001.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10001ActionPerformed(evt);
            }
        });

        Box10002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10002.setForeground(new java.awt.Color(0, 255, 0));
        Box10002.setText("1000");
        Box10002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10002ActionPerformed(evt);
            }
        });

        Box2002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2002.setForeground(new java.awt.Color(0, 255, 0));
        Box2002.setText("200");
        Box2002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2002ActionPerformed(evt);
            }
        });

        Box6002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6002.setForeground(new java.awt.Color(0, 255, 0));
        Box6002.setText("600");
        Box6002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6002ActionPerformed(evt);
            }
        });

        Box8002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8002.setForeground(new java.awt.Color(0, 255, 0));
        Box8002.setText("800");
        Box8002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8002ActionPerformed(evt);
            }
        });

        Box4002.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4002.setForeground(new java.awt.Color(0, 255, 0));
        Box4002.setText("400");
        Box4002.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4002ActionPerformed(evt);
            }
        });

        Box4003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4003.setForeground(new java.awt.Color(0, 255, 0));
        Box4003.setText("400");
        Box4003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4003ActionPerformed(evt);
            }
        });

        Box6003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6003.setForeground(new java.awt.Color(0, 255, 0));
        Box6003.setText("600");
        Box6003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6003ActionPerformed(evt);
            }
        });

        Box8003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8003.setForeground(new java.awt.Color(0, 255, 0));
        Box8003.setText("800");
        Box8003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8003ActionPerformed(evt);
            }
        });

        Box10003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10003.setForeground(new java.awt.Color(0, 255, 0));
        Box10003.setText("1000");
        Box10003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10003ActionPerformed(evt);
            }
        });

        Box2003.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2003.setForeground(new java.awt.Color(0, 255, 0));
        Box2003.setText("200");
        Box2003.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2003ActionPerformed(evt);
            }
        });

        Box10004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box10004.setForeground(new java.awt.Color(0, 255, 0));
        Box10004.setText("1000");
        Box10004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box10004ActionPerformed(evt);
            }
        });

        Box6004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6004.setForeground(new java.awt.Color(0, 255, 0));
        Box6004.setText("600");
        Box6004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6004ActionPerformed(evt);
            }
        });

        Box2004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2004.setForeground(new java.awt.Color(0, 255, 0));
        Box2004.setText("200");
        Box2004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2004ActionPerformed(evt);
            }
        });

        Box4004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4004.setForeground(new java.awt.Color(0, 255, 0));
        Box4004.setText("400");
        Box4004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4004ActionPerformed(evt);
            }
        });

        Box8004.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8004.setForeground(new java.awt.Color(0, 255, 0));
        Box8004.setText("800");
        Box8004.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8004ActionPerformed(evt);
            }
        });

        Box2005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box2005.setForeground(new java.awt.Color(0, 255, 0));
        Box2005.setText("200");
        Box2005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box2005ActionPerformed(evt);
            }
        });

        Box6005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box6005.setForeground(new java.awt.Color(0, 255, 0));
        Box6005.setText("600");
        Box6005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box6005ActionPerformed(evt);
            }
        });

        Box8005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box8005.setForeground(new java.awt.Color(0, 255, 0));
        Box8005.setText("800");
        Box8005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box8005ActionPerformed(evt);
            }
        });

        Box4005.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box4005.setForeground(new java.awt.Color(0, 255, 0));
        Box4005.setText("400");
        Box4005.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box4005ActionPerformed(evt);
            }
        });

        Box1000.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        Box1000.setForeground(new java.awt.Color(0, 255, 0));
        Box1000.setText("1000");
        Box1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box1000ActionPerformed(evt);
            }
        });

        jButton48.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jButton48.setText("Famous Woman");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });

        jButton51.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jButton51.setText("Years");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });

        jButton52.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jButton52.setText("Movies");
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });

        jButton53.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jButton53.setText("Breakfast");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });

        jButton54.setFont(new java.awt.Font("Yu Gothic Medium", 1, 10)); // NOI18N
        jButton54.setText("Presidents");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Your Score");

        ScoreBox.setColumns(20);
        ScoreBox.setRows(5);
        jScrollPane1.setViewportView(ScoreBox);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("The Question");

        QuestionBox.setColumns(20);
        QuestionBox.setRows(5);
        QuestionBox.setWrapStyleWord(true);
        jScrollPane2.setViewportView(QuestionBox);

        jButton1.setText("Click Here!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Your Answer");

        AnswerBox.setColumns(20);
        AnswerBox.setRows(5);
        jScrollPane3.setViewportView(AnswerBox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Box2001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Box4001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Box6001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Box8001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Box10001, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton48, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Box2002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box4002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box6002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box8002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box10002, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Box2003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box4003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box6003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box8003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box10003, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Box2004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box4004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box6004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box8004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box10004, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Box2005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box4005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box6005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box8005, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Box1000, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addGap(0, 134, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box2001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box4001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box6001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box8001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box10001, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box2002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box4002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box6002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box8002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box10002, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box2003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box4003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box6003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box8003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box10003, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box2005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box4005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box6005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box8005, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box1000, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Box2004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box4004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box6004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box8004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box10004, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(56, 56, 56))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Box2001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2001ActionPerformed
        QuestionBox.setText("In 1932 she made Headlines for being the First woman to fly a  solo transatlantic Flight");
    }//GEN-LAST:event_Box2001ActionPerformed

    private void Box8001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8001ActionPerformed
        QuestionBox.setText("She was Princess of Wales and Died in 1997 following a car crash");
    }//GEN-LAST:event_Box8001ActionPerformed

    private void Box2002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2002ActionPerformed
       QuestionBox.setText("After Six Years it WWII ended on September 2 of his Year ");
    }//GEN-LAST:event_Box2002ActionPerformed

    private void Box8002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8002ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box8002ActionPerformed

    private void Box8003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8003ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box8003ActionPerformed

    private void Box2003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2003ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box2003ActionPerformed

    private void Box2004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2004ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box2004ActionPerformed

    private void Box8004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8004ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box8004ActionPerformed

    private void Box2005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box2005ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box2005ActionPerformed

    private void Box8005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box8005ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box8005ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
         QuestionBox.setText("");
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
         QuestionBox.setText("");
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Box4001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4001ActionPerformed
        QuestionBox.setText("She was a Former First Lady and Later Ran for President of the US but failed ");
    }//GEN-LAST:event_Box4001ActionPerformed

    private void Box6001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6001ActionPerformed
         QuestionBox.setText("She Died in the Holocaust but became famous after her death when her diary as found");
    }//GEN-LAST:event_Box6001ActionPerformed

    private void Box10001ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10001ActionPerformed
         QuestionBox.setText("She Has the Second Most single titles in women's Tennis grand Slam Tournaments at 23");
    }//GEN-LAST:event_Box10001ActionPerformed

    private void Box4002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4002ActionPerformed
        QuestionBox.setText("WWI Started pn July 28th of This Year");
    }//GEN-LAST:event_Box4002ActionPerformed

    private void Box6002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6002ActionPerformed
         QuestionBox.setText("");
    }//GEN-LAST:event_Box6002ActionPerformed

    private void Box10002ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10002ActionPerformed
         QuestionBox.setText("");
    }//GEN-LAST:event_Box10002ActionPerformed

    private void Box4003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4003ActionPerformed
         QuestionBox.setText("");
    }//GEN-LAST:event_Box4003ActionPerformed

    private void Box6003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6003ActionPerformed
         QuestionBox.setText("");
    }//GEN-LAST:event_Box6003ActionPerformed

    private void Box10003ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10003ActionPerformed
         QuestionBox.setText("");
    }//GEN-LAST:event_Box10003ActionPerformed

    private void Box4004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4004ActionPerformed
         QuestionBox.setText("");
    }//GEN-LAST:event_Box4004ActionPerformed

    private void Box6004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6004ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box6004ActionPerformed

    private void Box10004ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box10004ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box10004ActionPerformed

    private void Box4005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box4005ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box4005ActionPerformed

    private void Box6005ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box6005ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box6005ActionPerformed

    private void Box1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box1000ActionPerformed
        QuestionBox.setText("");
    }//GEN-LAST:event_Box1000ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scene1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scene1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scene1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scene1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scene1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AnswerBox;
    private javax.swing.JButton Box1000;
    private javax.swing.JButton Box10001;
    private javax.swing.JButton Box10002;
    private javax.swing.JButton Box10003;
    private javax.swing.JButton Box10004;
    private javax.swing.JButton Box2001;
    private javax.swing.JButton Box2002;
    private javax.swing.JButton Box2003;
    private javax.swing.JButton Box2004;
    private javax.swing.JButton Box2005;
    private javax.swing.JButton Box4001;
    private javax.swing.JButton Box4002;
    private javax.swing.JButton Box4003;
    private javax.swing.JButton Box4004;
    private javax.swing.JButton Box4005;
    private javax.swing.JButton Box6001;
    private javax.swing.JButton Box6002;
    private javax.swing.JButton Box6003;
    private javax.swing.JButton Box6004;
    private javax.swing.JButton Box6005;
    private javax.swing.JButton Box8001;
    private javax.swing.JButton Box8002;
    private javax.swing.JButton Box8003;
    private javax.swing.JButton Box8004;
    private javax.swing.JButton Box8005;
    private javax.swing.JTextArea QuestionBox;
    private javax.swing.JTextArea ScoreBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
